MODES = [
    'DINO_PRETRAINED_EVAL',
    'RANDOM_INIT_EVAL',
    'SCRATCH_IMAGENET_SIMCLR_PRETRAIN',
    'SCRATCH_IMAGENET_SUPERVISED_PRETRAIN',
    'DINO_IMAGENET_SIMCLR_FINETUNE',
    'DINO_IMAGENET_SUPERVISED_FINETUNE',
    'DINO_CIFAR_SUPERVISED_FINETUNE',
    'SCRATCH_CIFAR_SUPERVISED_TRAIN',
]
